// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX13XzoGgdua0opv4gKYk62ckczolywnI',
    appId: '1:790949395301:web:fe3a0dff461a5b7ce3bf8c',
    messagingSenderId: '790949395301',
    projectId: 'martialartconnect',
    authDomain: 'martialartconnect.firebaseapp.com',
    storageBucket: 'martialartconnect.appspot.com',
    measurementId: 'G-8TKLFMVQH5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxqUBF69wwKU3iSSCA4MLkrtuGcDBIrTQ',
    appId: '1:790949395301:android:8b1278c6042aaeb0e3bf8c',
    messagingSenderId: '790949395301',
    projectId: 'martialartconnect',
    storageBucket: 'martialartconnect.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBafWvyTWHiOK0vBG3mmKuF5PIH1fz_f78',
    appId: '1:790949395301:ios:0d7698d5327be387e3bf8c',
    messagingSenderId: '790949395301',
    projectId: 'martialartconnect',
    storageBucket: 'martialartconnect.appspot.com',
    iosBundleId: 'com.example.martialartconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBafWvyTWHiOK0vBG3mmKuF5PIH1fz_f78',
    appId: '1:790949395301:ios:b1d54e8108614f9ce3bf8c',
    messagingSenderId: '790949395301',
    projectId: 'martialartconnect',
    storageBucket: 'martialartconnect.appspot.com',
    iosBundleId: 'com.example.martialartconnect.RunnerTests',
  );
}
